<a href="https://colab.research.google.com/github/anasabbad/Playground/blob/main/Flight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Libraries and Loading the data set**

In [ ]:
# Importing the libraries
import numpy as np
import pandas as pd
from numpy import math
from scipy import stats

import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#mounting the drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#loading the data
data= pd.read_csv('/content/drive/MyDrive/DataSets/gpu.csv')

In [ ]:
data.head()

,Architecture,Best_Resolution,Boost_Clock,Core_Speed,DVI_Connection,Dedicated,Direct_X,DisplayPort_Connection,HDMI_Connection,Integrated,...,Process,ROPs,Release_Date,Release_Price,Resolution_WxH,SLI_Crossfire,Shader,TMUs,Texture_Rate,VGA_Connection
0,Tesla G92b,NaN,NaN,738 MHz,2.0,Yes,DX 10.0,NaN,0.0,No,...,55nm,16,\n01-Mar-2009,NaN,2560x1600,Yes,4.0,64.0,47 GTexel/s,0.0
1,R600 XT,1366 x 768,NaN,\n-,2.0,Yes,DX 10,NaN,0.0,No,...,80nm,16,\n14-May-2007,NaN,2560x1600,Yes,4.0,16.0,12 GTexel/s,0.0
2,R600 PRO,1366 x 768,NaN,\n-,2.0,Yes,DX 10,NaN,0.0,No,...,80nm,16,\n07-Dec-2007,NaN,2560x1600,Yes,4.0,16.0,10 GTexel/s,0.0
3,RV630,1024 x 768,NaN,\n-,2.0,Yes,DX 10,NaN,0.0,No,...,65nm,4,\n01-Jul-2007,NaN,2560x1600,Yes,4.0,8.0,7 GTexel/s,0.0
4,RV630,1024 x 768,NaN,\n-,2.0,Yes,DX 10,NaN,0.0,No,...,65nm,4,\n28-Jun-2007,NaN,2560x1600,Yes,4.0,8.0,6 GTexel/s,0.0

**We need to split the colimns using ',' as the delimiter and rename the columns**

In [ ]:
data = data.dropna(how='any',axis=0)

In [ ]:
# split column into multiple columns by delimiter
data=data['year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute'].str.split(',', expand=True)
print(data)

        0  1  2     3   4     5    6   7       8     9    10   11   12    13  \
0     2013  1  1   517   2   830   11  UA  N14228  1545  EWR  IAH  227  1400
1     2013  1  1   533   4   850   20  UA  N24211  1714  LGA  IAH  227  1416
2     2013  1  1   542   2   923   33  AA  N619AA  1141  JFK  MIA  160  1089
3     2013  1  1   554  -6   812  -25  DL  N668DN   461  LGA  ATL  116   762
4     2013  1  1   554  -4   740   12  UA  N39463  1696  EWR  ORD  150   719
...    ... .. ..   ...  ..   ...  ...  ..     ...   ...  ...  ...  ...   ...
3070  2013  1  8  1348  68  1639   44  AA  N5DSAA  2041  JFK  MIA  153  1089
3071  2013  1  8  1350   0  1651  -24  US  N654AW   688  EWR  PHX  281  2133
3072  2013  1  8  1352  -8  1503    0  US  N947UW  2130  LGA  BOS   38   184
3073  2013  1  8  1353   3  1650  -18  UA  N37413  1164  EWR  FLL  154  1065
3074  2013  1  8  1353  -7  1508   -1  US  N712US  2177  LGA  DCA   41   214

      14    15
0      5    17
1      5    33
2      5    42
3      5    54
4      5    54
...   ..   ...
3070  13    48
3071  13    50
3072  13    52
3073  13    53
3074  13  None

[3075 rows x 16 columns]

In [ ]:
data.head()

     0  1  2    3   4    5    6   7       8     9    10   11   12    13 14  15
0  2013  1  1  517   2  830   11  UA  N14228  1545  EWR  IAH  227  1400  5  17
1  2013  1  1  533   4  850   20  UA  N24211  1714  LGA  IAH  227  1416  5  33
2  2013  1  1  542   2  923   33  AA  N619AA  1141  JFK  MIA  160  1089  5  42
3  2013  1  1  554  -6  812  -25  DL  N668DN   461  LGA  ATL  116   762  5  54
4  2013  1  1  554  -4  740   12  UA  N39463  1696  EWR  ORD  150   719  5  54

In [ ]:
#Renaming the columns
cols = ['year','month','day','dep_time','dep_delay','arr_time','arr_delay','carrier','tailnum','flight','origin','dest','air_time','distance','hour','minute']
data.columns = cols
print(data.columns)

Index(['year', 'month', 'day', 'dep_time', 'dep_delay', 'arr_time',
       'arr_delay', 'carrier', 'tailnum', 'flight', 'origin', 'dest',
       'air_time', 'distance', 'hour', 'minute'],
      dtype='object')

In [ ]:
data.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517,2,830,11,UA,N14228,1545,EWR,IAH,227,1400,5,17
1,2013,1,1,533,4,850,20,UA,N24211,1714,LGA,IAH,227,1416,5,33
2,2013,1,1,542,2,923,33,AA,N619AA,1141,JFK,MIA,160,1089,5,42
3,2013,1,1,554,-6,812,-25,DL,N668DN,461,LGA,ATL,116,762,5,54
4,2013,1,1,554,-4,740,12,UA,N39463,1696,EWR,ORD,150,719,5,54

# 2. Handling missing values

In [ ]:
data.shape

(3075, 16)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 288 entries, 45 to 3278
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Architecture            288 non-null    object
 1   Best_Resolution         288 non-null    object
 2   Boost_Clock             288 non-null    object
 3   Core_Speed              288 non-null    object
 4   DVI_Connection          288 non-null    float64
 5   Dedicated               288 non-null    object
 6   Direct_X                288 non-null    object
 7   DisplayPort_Connection  288 non-null    float64
 8   HDMI_Connection         288 non-null    float64
 9   Integrated              288 non-null    object
 10  L2_Cache                288 non-null    object
 11  Manufacturer            288 non-null    object
 12  Max_Power               288 non-null    object
 13  Memory                  288 non-null    object
 14  Memory_Bandwidth        288 non-null    object
 15  Memory_Bus              288 non-null    object
 16  Memory_Speed            288 non-null    object
 17  Memory_Type             288 non-null    object
 18  Name                    288 non-null    object
 19  Notebook_GPU            288 non-null    object
 20  Open_GL                 288 non-null    float64
 21  PSU                     288 non-null    object
 22  Pixel_Rate              288 non-null    object
 23  Power_Connector         288 non-null    object
 24  Process                 288 non-null    object
 25  ROPs                    288 non-null    object
 26  Release_Date            288 non-null    object
 27  Release_Price           288 non-null    object
 28  Resolution_WxH          288 non-null    object
 29  SLI_Crossfire           288 non-null    object
 30  Shader                  288 non-null    float64
 31  TMUs                    288 non-null    float64
 32  Texture_Rate            288 non-null    object
 33  VGA_Connection          288 non-null    float64
dtypes: float64(7), object(27)
memory usage: 78.8+ KB

In [ ]:
data.to_csv('file_name.csv', index=False)

**From this we can see that there is no columns with missing values.**

# Changing the data type of the features

In [ ]:
data['dep_delay'] = data['dep_delay'].replace(regex='([a-zA-Z])', value=0)

In [ ]:
data=data.astype({'year':'int', 'month':'int', 'day':'int','distance':'int','dep_delay':'int'})

In [ ]:
#data['dep_delay'] = pd.to_numeric(data['dep_delay'][:, 0], errors='coerce').fillna(0)
data['dep_delay'] = data['dep_delay'].replace(regex='([a-zA-Z])', value=0)

In [ ]:
data["arr_delay"] = pd.to_numeric(data["arr_delay"],errors='coerce')
data["arr_time"] = pd.to_numeric(data["arr_time"],errors='coerce')
data["air_time"] = pd.to_numeric(data["air_time"],errors='coerce')
data["hour"] = pd.to_numeric(data["hour"],errors='coerce')
data["minute"] = pd.to_numeric(data["minute"],errors='coerce')
data["dep_time"] = pd.to_numeric(data["dep_time"],errors='coerce')
#data["dep_delay"] = pd.to_numeric(data["dep_delay"],errors='coerce')

In [ ]:
data.dropna()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,554.0,-6,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
4,2013,1,1,554.0,-4,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3069,2013,1,8,1344.0,3,1951.0,16.0,UA,N77066,15,EWR,HNL,645.0,4963,13.0,44.0
3070,2013,1,8,1348.0,68,1639.0,44.0,AA,N5DSAA,2041,JFK,MIA,153.0,1089,13.0,48.0
3071,2013,1,8,1350.0,0,1651.0,-24.0,US,N654AW,688,EWR,PHX,281.0,2133,13.0,50.0
3072,2013,1,8,1352.0,-8,1503.0,0.0,US,N947UW,2130,LGA,BOS,38.0,184,13.0,52.0
3073,2013,1,8,1353.0,3,1650.0,-18.0,UA,N37413,1164,EWR,FLL,154.0,1065,13.0,53.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3075 entries, 0 to 3074
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   year       3075 non-null   int64
 1   month      3075 non-null   int64
 2   day        3075 non-null   int64
 3   dep_time   3055 non-null   float64
 4   dep_delay  3075 non-null   int64
 5   arr_time   3054 non-null   float64
 6   arr_delay  3051 non-null   float64
 7   carrier    3075 non-null   object
 8   tailnum    3075 non-null   object
 9   flight     3075 non-null   object
 10  origin     3075 non-null   object
 11  dest       3075 non-null   object
 12  air_time   3051 non-null   float64
 13  distance   3075 non-null   int64
 14  hour       3055 non-null   float64
 15  minute     3054 non-null   float64
dtypes: float64(6), int64(5), object(5)
memory usage: 384.5+ KB

# 1. Descriptive statistics for Continuous Variables

In [ ]:
data.describe()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,air_time,distance,hour,minute
count,3075.0,3075.0,3075.000000,3055.000000,3075.000000,3054.000000,3051.000000,3051.000000,3075.000000,3055.000000,3054.000000
mean,2013.0,1.0,4.241951,1274.773159,5.438699,1518.542567,-2.461488,189.944608,1296.359675,12.431751,31.591028
std,0.0,0.0,2.213108,458.355981,25.771134,480.692366,29.578405,92.542519,728.066074,4.595260,18.659535
min,2013.0,1.0,1.000000,454.000000,-19.000000,3.000000,-63.000000,27.000000,94.000000,4.000000,0.000000
25%,2013.0,1.0,2.000000,842.500000,-4.000000,1116.000000,-18.000000,125.000000,746.000000,8.000000,15.000000
50%,2013.0,1.0,4.000000,1253.000000,-1.000000,1521.000000,-7.000000,162.000000,1085.000000,12.000000,31.000000
75%,2013.0,1.0,6.000000,1700.000000,4.000000,1935.000000,7.000000,248.000000,1620.000000,17.000000,50.000000
max,2013.0,1.0,8.000000,2259.000000,379.000000,2359.000000,368.000000,656.000000,4963.000000,22.000000,59.000000

## Descriptive Statistics for Categorical Variables

In [ ]:
data.describe(include='object')

       carrier tailnum flight origin  dest
count     3075    3075   3075   3075  3075
unique       5    1205    836      3    48
top         UA  N951UW    695    EWR   MIA
freq      1149      11     17   1162   240

Here **top** represents the **mode** of the the categorical variable

In [ ]:
data.var(numeric_only=True)

year              0.000000
month             0.000000
day               4.897849
dep_time     210090.204911
dep_delay       664.151332
arr_time     231065.150333
arr_delay       874.882041
air_time       8564.117914
distance     530080.208263
hour             21.116411
minute          348.178249
dtype: float64

In [ ]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

numerical_data = data.select_dtypes(include=numerics)

## 3. Most delayed departure airport

In [ ]:
#index of the max value of a delayed departure
max_index = data['dep_delay'].idxmax()
max_index

852

In [ ]:
departure_airport=data.origin[max_index]
print("Most Delayed Departure Airport: ", departure_airport)

Most Delayed Departure Airport:  LGA

# 4. Least delayed Arrival airport

In [ ]:
min_index = data['dep_delay'].idxmin()
min_index

1696

In [ ]:
arrival=data.dest[min_index]
print("Least Delayed Departure Airport: ", arrival)

Leas Delayed Departure Airport:  PWM

# 5. Flight with Maximum Airtime

In [ ]:
max_air_index = data['air_time'].idxmax()
max_air_index

204

In [ ]:
max_air_time_flight=data.flight[max_air_index]
max_air_tail_number= data.tailnum[max_air_index]
print(" Flight with Maximum Airtime: ", max_air_time_flight)
print(" Tail Number: ", max_air_tail_number)

 Flight with Maximum Airtime:  15
 Tail Number:  N76065

# 6. Flight which covered Maximum distance

In [ ]:
max_dist_index = data['distance'].idxmax()
max_dist_index

204

In [ ]:
data.flight[204]
max_distance_flight=data.flight[max_dist_index]
max_dist_tail_number= data.tailnum[max_dist_index]
print(" Flight with Maximum Airtime: ", max_distance_flight)
print(" Tail Number: ", max_dist_tail_number)

 Flight with Maximum Airtime:  15
 Tail Number:  N76065